const routes = {
    home: '/',
    admin: '/admin/dashboard',
    recruiter: '/recruiter/manager',
    recruiterPostSidebar: '/recruiter/post',
    recruiterPostManageSidebar: '/recruiter/managelistpost',
    ListPostOfRecruiter: '/recruiter/ListPostOfRecruiter',
    ListRecruitmentPost: '/recruiter/listpost',
    profile: '/profile',
    settings: '/settings',
    accounts: '/accounts',
    blog: '/blog/listblog',
    cv: '/cv',
    recruitment: '/recruitmentpage',
    testuser: '/testuser',
    marketing: '/testuser/marketing',
    businessadministration: '/testuser/businessadministration',
    linguistics: '/testuser/linguistics',
    manageBlog: '/blog/postblog/:id',
    usersManagement: '/admin/usermanagement',
    recruiterpost: '/recruiter/recruiterpostjob',
    recruitmentdetail: 'recruitmentpage/recruitmentdetail/:recruitmentId',
    recruitmentpage: '/recruitmentpage/user',
    savepost: '/savedpost/savedRecruitment',
    saveblog: '/savedpost/savedBlog',
    saverecruitment: '/post/recruitmentsaved',
    editPost: '/recruiter/recruiterpostjob/:id',
    createblog: '/blog',
    postblog: '/blog/postblog',
    blogcontent: '/blog/postblog/blogcontent',
    blogdetail: '/blog/listblog/blogdetail/:id',
    blogdetail2: '/blog/myblog/blogdetail/:id',
    blogcontentrecuiter: '/dashboard/blog/listblog',
    rank: '/leaderboard/:id',
    myblog: '/blog/myblog',
    recruiterManageCandidates: '/recruiter/manage-candidates',
};

export default routes;
