const routes = {
    home: '/',
    admin: '/admin/dashboard',
    recruiter: '/recruiter/manager',
    recruiterPostSidebar: '/recruiter/post',
    recruiterPostManageSidebar: '/recruiter/managelistpost',
    ListPostOfRecruiter: '/recruiter/ListPostOfRecruiter',
    ListRecruitmentPost: '/recruiter/listpost',
    ListRecruitmentPostBlock: '/recruiter/listpostblock',
    profile: '/profile',
    settings: '/settings',
    accounts: '/accounts',
    re: '/reauto/listreauto',
    redetail : '/reauto/listreauto/:id',
    cv: '/cv',
    editcv : 'cv/:id',
    recruitment: '/recruitmentpage',
    managecv : '/manager-cv',
    usersManagement: '/admin/usermanagement',
    recruiterpost: '/recruiter/recruiterpostjob',
    recruitmentdetail: 'recruitmentpage/recruitmentdetail/:id',
    recruitmentpage: '/recruitmentpage/user',
    saverecruitment: '/post/recruitmentsaved',
    editPost: '/recruiter/recruiterpostjob/:id',
    recruiterManageCandidates: '/recruiter/manage-candidates',
    blog: '/blog/listblog',
    manageBlog: '/blog/postblog/:id',
    saveblog: '/savedpost/savedBlog',
    createblog: '/blog',
    postblog: '/blog/postblog',
    blogcontent: '/blog/postblog/blogcontent',
    blogdetail: '/blog/listblog/blogdetail/:id',
    blogdetail2: '/blog/myblog/blogdetail/:id',
    showquizrecuiter: '/recruiter/showquizrecuiter',
    blogcontentrecuiter: '/dashboard/blog/listblog',
    myblog: '/blog/myblog',
};

export default routes;
